export const FETCH_SEARCH_REQUEST = "FETCH_SEARCH_REQUEST";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FIRST_SCREEN_TOGGLE = "FIRST_SCREEN_TOGGLE";
export const SELECT_OPTION = "SELECT_OPTION";
export const SORT_BY_TITLE_A_Z = "SORT_BY_TITLE_A_Z";
export const SORT_BY_TITLE_Z_A = "SORT_BY_TITLE_Z_A";
export const SORT_BY_DATE_ASC = "SORT_BY_DATE_ASC";
export const SORT_BY_DATE_DESC = "SORT_BY_DATE_DESC";
export const FETCH_AUTHOR_SUCCESS = "FETCH_AUTHOR_SUCCESS";
export const SORT_DATE = "SORT_DATE";

